POST http://localhost/api/rackets
content-type: application/json

{
    {
      "name":"ADIDAS ADIPOWER CTRL 3.0",
      "year":"2021",
      "weight":"280",
      "width":"26",
      "age":"ADULT",
      "balance":"MEDIUM",
      "color":"ORANGE",
      "core":"MID EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21766-53487e46-23353-NORMAL.jpg"
    },
    {
      "name":"ADIDAS ADIPOWER CTRL LITE",
      "year":"2021",
      "weight":"280",
      "width":"26",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"ORANGE",
      "core":"SOFT EVA RUBBER",
      "face":"GLASS FIBER",
      "frame":"FIBREGLASS",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21773-06d279de-23368-NORMAL.jpg"
    },
    {
      "name":"ADIDAS ADIPOWER JUNIOR 3.0",
      "year":"2021",
      "weight":"320",
      "width":"35",
      "age":"KIDS",
      "Balance":"MEDIUM",
      "Colour":"GREY BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"FIBREGLASS",
      "gender":"UNISEX",
      "gameLevel":"BEGINNERS",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21779-57bc8675-23355-NORMAL.jpg"
    },
    {
      "name":"ADIDAS ADIPOWER LIGHT 2.0",
      "year":"2020",
      "weight":"320",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"GREY",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-19105-1ad3f99d-19816-NORMAL.jpg"
    },
    {
      "name":"ADIDAS ADIPOWER LIGHT 3.0",
      "year":"2020",
      "weight":"340",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"FEMALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21767-e5332038-23356-NORMAL.jpg"
    },
    {
      "name":"ADIDAS ADIPOWER SOFT 2.0",
      "year":"2020",
      "weight":"345",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"GREY RED",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"OVERSIZE DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-19104-9cc7f5d4-19810-NORMAL.jpg"
    },
    {
      "name":"ADIDAS ADIPOWER WOMAN LITE",
      "year":"2021",
      "weight":"345",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"PINK",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"GLASS FIBER",
      "gender":"FEMALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21774-27fa631f-23369-NORMAL.jpg"
    },
    {
      "name":"ADIDAS CARBON CTRL 2.0",
      "year":"2020",
      "weight":"355",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK GREEN",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON FIBER",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-19106-ceb4a463-19822-NORMAL.jpg"
    },
    {
      "name":"ADIDAS DRIVE 3.0",
      "year":"2021",
      "weight":"360",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLACK BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"FIBREGLASS",
      "gender":"UNISEX",
      "gameLevel":"BEGINNERS",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21780-f64f60e6-23360-NORMAL.jpg"
    },
    {
      "name":"ADIDAS FASTER GREEN 1.9",
      "year":"2019",
      "weight":"360",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"GREEN",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-17022-c878781d-16770-NORMAL.jpg"
    },
    {
      "name":"ADIDAS GREENPADEL",
      "year":"2021",
      "weight":"360",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"GREEN",
      "core":"MID EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21771-820279d4-23365-NORMAL.jpg"
    },
    {
      "name":"ADIDAS MATCH LIGHT 3.0",
      "year":"2021",
      "weight":"360",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH / MEDIUM",
      "Colour":"BLACK ORANGE",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"FIBREGLASS",
      "gender":"UNISEX",
      "gameLevel":"BEGINNERS",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21782-298ca54d-23363-NORMAL.jpg"
    },
    {
      "name":"ADIDAS MATCH LTD",
      "year":"2021",
      "weight":"360",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"GREEN",
      "core":"MID EVA RUBBER",
      "face":"GLASS FIBER",
      "frame":"CARBON TUBULAR",
      "gender":"MALE",
      "gameLevel":"BEGINNERS",
      "shape":"DIAMOND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-22962-ccd67d36-24048-NORMAL.jpg"
    },
    {
      "name":"ADIDAS METALBONE",
      "year":"2021",
      "weight":"360",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"RED",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21762-3286906e-23338-NORMAL.jpg"
    },
    {
      "name":"ADIDAS METALBONE CTRL",
      "year":"2021",
      "weight":"360",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21763-487d20c2-23341-NORMAL.jpg"
    },
    {
      "name":"ADIDAS METALBONE YOUTH",
      "year":"2021",
      "weight":"365",
      "width":"38",
      "age":"KIDS",
      "Balance":"HIGH",
      "Colour":"GREY RED",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"FIBREGLASS",
      "gender":"UNISEX",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"OVERSIZE DIAMOND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21778-9639f615-23354-NORMAL.jpg"
    },
    {
      "name":"ADIDAS RADOGAR ATTK",
      "year":"2021",
      "weight":"365",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"GLASS FIBER",
      "frame":"CARBON TUBULAR",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-22963-1ac28e5d-24052-NORMAL.jpg"
    },
    {
      "name":"ADIDAS RADOGAR CTRL ORANGE",
      "year":"2021",
      "weight":"365",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"ORANGE",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-23539-0267e917-24240-NORMAL.jpg"
    },
    {
      "name":"ADIDAS RX10",
      "year":"2021",
      "weight":"365",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK GREEN",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"FIBREGLASS",
      "gender":"UNISEX",
      "gameLevel":"INTERMEDIATE",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21777-1f6f78a2-23351-NORMAL.jpg"
    },
    {
      "name":"ADIDAS RX20 LIGHT",
      "year":"2021",
      "weight":"365",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK ORANGE",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"FIBREGLASS",
      "gender":"UNISEX",
      "gameLevel":"INTERMEDIATE",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21776-c17190ed-23342-NORMAL.jpg"
    },
    {
      "name":"ADIDAS RX30",
      "year":"2021",
      "weight":"365",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK YELLOW",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"FIBREGLASS",
      "gender":"UNISEX",
      "gameLevel":"INTERMEDIATE",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21775-1f4ab212-23340-NORMAL.jpg"
    },
    {
      "name":"ADIDAS RYZE PRO",
      "year":"2021",
      "weight":"370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"YELLOW",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-23540-db2425ef-24237-NORMAL.jpg"
    },
    {
      "name":"ADIDAS RYZE PRO WOMAN",
      "year":"2021",
      "weight":"370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"PINK",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"FEMALE",
      "gameLevel":"BEGINNERS / INTERMEDIATE",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-23541-0e0dc1bf-24239-NORMAL.jpg"
    },
    {
      "name":"ADIDAS VORTOM SOFT BLUE",
      "year":"2021",
      "weight":"370",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"3K CARBON",
      "frame":"CARBON TUBULAR",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-22964-93c11440-24054-NORMAL.jpg"
    },
    {
      "name":"ADIDAS VORTOM SOFT LITE BLUE",
      "year":"2021",
      "weight":"375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLUE",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON TUBULAR",
      "gender":"UNISEX",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-22883-b2eae1fb-24056-NORMAL.jpg"
    },
    {
      "name":"ADIDAS VORTOM SOFT LITE RED",
      "year":"2021",
      "weight":"375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"RED",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON TUBULAR",
      "gender":"UNISEX",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-22965-bdcf6b6b-24058-NORMAL.jpg"
    },
    {
      "name":"ARES DARKNESS",
      "year":"2021",
      "weight":"300-325",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK PINK",
      "core":"EVA RUBBER",
      "face":"3K CARBON",
      "frame":"KEVLAR CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21168-4ad5d57f-22612-NORMAL.jpg"
    },
    {
      "name":"ARES SPEAR",
      "year":"2021",
      "weight":"310-330",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"PURPLE",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"FIBREGLASS",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-13415-a6cf6792-22618-NORMAL.jpg"
    },
    {
      "name":"BABOLAT AIR VERON",
      "year":"2021",
      "weight":"335-345",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"HYBRID",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21192-02c48817-22629-NORMAL.jpg"
    },
    {
      "name":"BABOLAT AIR VERTUO 2021",
      "year":"2021",
      "weight":"335-355",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLUE",
      "core":"BLACK EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"HYBRID",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21197-120de5fd-22635-NORMAL.jpg"
    },
    {
      "name":"BABOLAT COUNTER VERON",
      "year":"2021",
      "weight":"345",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21189-6dacb1fc-22621-NORMAL.jpg"
    },
    {
      "name":"BABOLAT COUNTER VIPER",
      "year":"2021",
      "weight":"345-360",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"GREY",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"3K CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21188-b9aab578-22619-NORMAL.jpg"
    },
    {
      "name":"BABOLAT REFLEX",
      "year":"2020",
      "weight":"345-360",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLUE GREY",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON FIBER",
      "gender":"MALE",
      "gameLevel":"BEGINNERS",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-19268-4dc79c9a-19967-NORMAL.jpg"
    },
    {
      "name":"BABOLAT TECHNICAL VERON",
      "year":"2021",
      "weight":"345-360",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK WHITE",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21187-303d711f-22620-NORMAL.jpg"
    },
    {
      "name":"BABOLAT TECHNICAL VERTUO 2021",
      "year":"2021",
      "weight":"345-360",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"RED",
      "core":"BLACK EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21196-ee586cc2-22632-NORMAL.jpg"
    },
    {
      "name":"BABOLAT TECHNICAL VIPER 2021",
      "year":"2021",
      "weight":"345-360",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK RED",
      "core":"EVA RUBBER",
      "face":"12K CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE / ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21193-d6d4b8d1-22631-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN GENIUS",
      "year":"2021",
      "weight":"350",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK GREEN",
      "core":"EVA RUBBER",
      "face":"3K CARBON",
      "frame":"CARBON BI-TUBULAR",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21848-3bef87e4-23446-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN OMNI",
      "year":"2018",
      "weight":"350-360",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK",
      "core":"BLACK EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-15704-c2cee934-14942-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN PITON 5.0",
      "year":"2017",
      "weight":"350-360",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"LILAC",
      "core":"BLACK EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON / CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE / ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/products/BLACKCROWN-PITON-5-0-2016-500X600-compressor.jpg"
    },
    {
      "name":"BLACK CROWN PITON 7.0",
      "year":"2018",
      "weight":"350-365",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLUE BLACK",
      "core":"SOFT EVA RUBBER",
      "face":"GLASS FIBER / CARBON FIBER",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-16067-9856470c-15464-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN PITON 8.0",
      "year":"2020",
      "weight":"350-365",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"RED",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON TUBULAR",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-19142-d0b7de16-19838-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN PITON 9.0",
      "year":"2021",
      "weight":"350-365",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK SILVER",
      "core":"BLACK EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON BI-TUBULAR",
      "gender":"UNISEX",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-23492-11792951-24211-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN PITON ATTACK",
      "year":"2019",
      "weight":"350-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK RED",
      "core":"SUPER SOFT EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-17212-c5518483-17149-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN PITON ATTACK 12K",
      "year":"2019",
      "weight":"350-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK GREEN",
      "core":"SUPER SOFT EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"12K CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-17213-e5e61b6b-17151-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN PITON NAKANO",
      "year":"2019",
      "weight":"350-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK PINK",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON FIBER",
      "gender":"FEMALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-18189-632aaeee-18169-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN PITON NAKANO 15K",
      "year":"2021",
      "weight":"355",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON FIBER",
      "gender":"UNISEX",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-23494-2e965c59-24215-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN PITON NAKANO 3K",
      "year":"2019",
      "weight":"355",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"WHITE BLUE",
      "core":"SUPER SOFT EVA RUBBER",
      "face":"FIBREGLASS / CARBON FIBER",
      "frame":"CARBON FIBER",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-19141-55bbf4e0-19837-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN POWER GENIUS",
      "year":"2021",
      "weight":"355",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"GREY RED",
      "core":"BLACK EVA RUBBER",
      "face":"12K CARBON",
      "frame":"CARBON BI-TUBULAR",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21849-50d5f759-23454-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN SHARK",
      "year":"2020",
      "weight":"355-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-19744-18a51fac-20638-NORMAL.jpg"
    },
    {
      "name":"BLACK CROWN WOLF",
      "year":"2020",
      "weight":"355-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLACK YELLOW",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"HYBRID",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-19745-e989b4ae-20639-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL BLACK DRAGON 3.0",
      "year":"2019",
      "weight":"355-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLACK ORANGE",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON AND GLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-18553-978ba808-18917-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL BRAVE 3.0",
      "year":"2021",
      "weight":"355-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"GREY YELLOW",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON TUBULAR",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"INVERTED DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24564-d9d61503-25319-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL FLOW",
      "year":"2021",
      "weight":"355-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLUE PINK",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"FEMALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21705-15042cb4-23305-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL FLOW LIGHT",
      "year":"2021",
      "weight":"355-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLUE PINK",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON",
      "gender":"UNISEX",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21716-fe4b8874-23301-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL GOLD 3.0",
      "year":"2021",
      "weight":"355-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"LILA",
      "core":"EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON TUBULAR",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24565-443bf249-25318-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL GOLD XSERIES 3.0",
      "year":"2021",
      "weight":"355-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"PURPLE",
      "core":"EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON TUBULAR",
      "gender":"FEMALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24563-b8b469dd-25309-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL HACK COMFORT 21",
      "year":"2021",
      "weight":"355-380",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK GREEN",
      "core":"EVA RUBBER",
      "face":"CARBON AND GLASS FIBER",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21709-faf7046c-23307-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL KITTER BLUE",
      "year":"2021",
      "weight":"356-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLUE",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"UNISEX",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24647-8ccbef49-25502-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL KITTER ORANGE",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"ORANGE",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24646-8c85cfcb-25499-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL LEGEND 3.0 2019",
      "year":"2019",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLACK BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-18142-13e34c18-18088-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL RAIDER PWR 460366",
      "year":"2021",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"GREEN BLACK",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"UNISEX",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21726-c9f5a3e9-23294-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL SHAKE",
      "year":"2021",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLACK BLUE",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"FIBREGLASS",
      "gender":"MALE",
      "gameLevel":"BEGINNERS",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21719-2f115e3a-23313-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL SKY 2019 BLUE",
      "year":"2019",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLACK BLUE",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-18143-1708c193-18091-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL SKY 2019 YELLOW",
      "year":"2019",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLACK YELLOW",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-18144-0b9d8428-18092-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL SKY PINK",
      "year":"2020",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLACK",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"UNISEX",
      "gameLevel":"INTERMEDIATE",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/products/BULLPADEL-SKY-PN-460351-800-1000-.jpg"
    },
    {
      "name":"BULLPADEL SKY RED",
      "year":"2021",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"RED",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"UNISEX",
      "gameLevel":"INTERMEDIATE",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24157-4f673fa5-24895-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL VERTEX 03 21",
      "year":"2021",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK",
      "core":"MID EVA RUBBER",
      "face":"CARBON",
      "frame":"12K CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21706-8e026d76-23296-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL VERTEX 03 CTR",
      "year":"2021",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLACK RED",
      "core":"EVA RUBBER",
      "face":"12K CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21707-3b3a7caf-23325-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL VERTEX 3 WOMAN",
      "year":"2021",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH / MEDIUM",
      "Colour":"FUCHSIA",
      "core":"EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON",
      "gender":"FEMALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21708-d2cead55-23315-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL VERTEX BLACK SERIES LTD",
      "year":"2020",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE / ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-19746-7ccdedf6-17045-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL VERTEX COMFORT",
      "year":"2021",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLUE RED",
      "core":"EVA RUBBER",
      "face":"CARBON AND GLASS FIBER",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21710-996f5f94-23303-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL WING",
      "year":"2021",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"ORANGE",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21712-22e778f5-23320-NORMAL.jpg"
    },
    {
      "name":"BULLPADEL WING BALANCE",
      "year":"2021",
      "weight":"360-370",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK YELLOW",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON BI-TUBULAR",
      "gender":"UNISEX",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-22923-253fb3b7-24008-NORMAL.jpg"
    },
    {
      "name":"DUNLOP AERO-STAR TEAM",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH / MEDIUM",
      "Colour":"BLACK RED",
      "core":"MID EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-22672-57eb3f9a-23930-NORMAL.jpg"
    },
    {
      "name":"DUNLOP BLITZ ELITE",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK GREEN",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"GRAPHITE",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"HYBRID",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-22679-823fa688-23947-NORMAL.jpg"
    },
    {
      "name":"DUNLOP EXPRESS BLUE",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLUE",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"GRAPHITE",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"HYBRID",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24385-df9aebd0-25185-NORMAL.jpg"
    },
    {
      "name":"DUNLOP EXPRESS YELLOW",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"YELLOW",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"GRAPHITE",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"HYBRID",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24384-c384eafe-25182-NORMAL.jpg"
    },
    {
      "name":"DUNLOP FUSION ELITE PRO RED",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"RED",
      "core":"MID EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"FIBREGLASS",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"HYBRID",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24387-ad001646-25186-NORMAL.jpg"
    },
    {
      "name":"DUNLOP INFERNO ELITE GOLD",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK GOLD",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"UNISEX",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"HYBRID",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24171-63a88d5f-25067-NORMAL.jpg"
    },
    {
      "name":"DUNLOP INFERNO ELITE SILVER",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLUE BLACK",
      "core":"SOFT EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"HYBRID",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24172-c0c6515d-25065-NORMAL.jpg"
    },
    {
      "name":"DUNLOP NEMESIS SILVER",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK SILVER",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"UNISEX",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24167-ef5e3457-25871-NORMAL.jpg"
    },
    {
      "name":"DUNLOP RENEGADE",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"BLACK GREEN",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"UNISEX",
      "gameLevel":"BEGINNERS",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21578-6f971797-23138-NORMAL.jpg"
    },
    {
      "name":"DUNLOP ROCKET GREEN",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK GREEN",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-23986-c3756563-24657-NORMAL.jpg"
    },
    {
      "name":"DUNLOP ROCKET YELLOW",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"YELLOW",
      "core":"EVA RUBBER",
      "face":"GLASS FIBER",
      "frame":"GRAPHITE",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24164-d93ced28-25354-NORMAL.jpg"
    },
    {
      "name":"DUNLOP SKIN ATTACK",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK YELLOW",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21581-1b49ddbc-23128-NORMAL.jpg"
    },
    {
      "name":"DUNLOP SKIN ATTACK SOFT",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK YELLOW",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"DIAMOND",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21576-ef8963a7-23139-NORMAL.jpg"
    },
    {
      "name":"DUNLOP SKIN CONTROL SOFT",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK RED",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21580-0fc0adfe-23129-NORMAL.jpg"
    },
    {
      "name":"DUNLOP SONIC",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK BLUE",
      "core":"ULTRA SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21577-b9caa315-23140-NORMAL.jpg"
    },
    {
      "name":"ECLYPSE LUNAR FUCHSIA 2.0",
      "year":"2018",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"INTERMEDIATE / LOW",
      "Colour":"BLACK FUCHSIA",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON",
      "gender":"FEMALE",
      "gameLevel":"INTERMEDIATE / ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-16357-5a91d35d-16021-NORMAL.jpg"
    },
    {
      "name":"ECLYPSE SOLAR 2.0",
      "year":"2018",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"BLACK YELLOW",
      "core":"EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-16348-cfccaab7-16023-NORMAL.jpg"
    },
    {
      "name":"ECLYPSE TOTAL 2.0",
      "year":"2018",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"RED BLACK",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-16350-1f42ea79-16022-NORMAL.jpg"
    },
    {
      "name":"ENEBE AEROX CARBON 21",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLUE BLACK",
      "core":"SOFT EVA RUBBER",
      "face":"3K CARBON",
      "frame":"CARBON TUBULAR",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24780-9e48fdfc-25601-NORMAL.jpg"
    },
    {
      "name":"ENEBE BREAK",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"GREY RED",
      "core":"EVA RUBBER",
      "face":"FIBREGLASS",
      "frame":"FIBREGLASS",
      "gender":"MALE",
      "gameLevel":"INTERMEDIATE",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24648-4e6615bb-25483-NORMAL.jpg"
    },
    {
      "name":"ENEBE COMBAT CARBON 21",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"YELLOW",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24778-ead1d73e-25602-NORMAL.jpg"
    },
    {
      "name":"ENEBE COMBAT REVOLUTION LADY",
      "year":"2019",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK PINK",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON FIBER",
      "gender":"FEMALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-18998-9e172db5-19703-NORMAL.jpg"
    },
    {
      "name":"ENEBE COMBAT ULTRASOFT",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLUE SKY",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"UNISEX",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24675-dad024a7-25557-NORMAL.jpg"
    },
    {
      "name":"ENEBE COMBAT WEAPON",
      "year":"2020",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"LOW",
      "Colour":"GREEN",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"ROUND",
      "gameType":"CONTROL",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-20479-cd490b77-21850-NORMAL.jpg"
    },
    {
      "name":"ENEBE ECLYPSE",
      "year":"2020",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK",
      "core":"MID EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-21478-97ca6337-23031-NORMAL.jpg"
    },
    {
      "name":"ENEBE KAZA",
      "year":"2019",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK ORANGE",
      "core":"SOFT EVA RUBBER",
      "face":"CARBON FIBER",
      "frame":"CARBON FIBER",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-19001-4cd75f62-19706-NORMAL.jpg"
    },
    {
      "name":"ENEBE METEOR 2",
      "year":"2020",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"HIGH",
      "Colour":"RED",
      "core":"BLACK EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POWER",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-20478-1ea0f646-21847-NORMAL.jpg"
    },
    {
      "name":"ENEBE RSX CARBON 21",
      "year":"2021",
      "weight":"360-375",
      "width":"38",
      "age":"ADULT",
      "Balance":"MEDIUM",
      "Colour":"BLACK RED",
      "core":"EVA RUBBER",
      "face":"CARBON",
      "frame":"CARBON",
      "gender":"MALE",
      "gameLevel":"ADVANCED PROFESSIONAL",
      "shape":"TEAR DROP",
      "gameType":"POLYVALENT",
      "imgUrl":"https://www.padelnuestro.com/images/cargador/productos/imagen-1-24779-eb98c5e5-25773-NORMAL.jpg"
    }
}